/**
 * Demo Security Events Data
 *
 * Mock security events for demo mode - events to test pagination and security alerts.
 * Includes failed login attempts (both regular and remote) after the most recent
 * successful login to demo security alerts.
 */

import type { SecurityEvent } from '../../types';

export const DEMO_SECURITY_EVENTS: SecurityEvent[] = [
  {
    id: 1,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 min ago - last successful login
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 5,
    event_type: 'REMOTE_UNLOCK',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 6,
    event_type: 'UNLOCK_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 7,
    event_type: 'LOGIN_ATTEMPT',
    success: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    ip_address: '91.243.82.116',
    country: 'Russia',
    city: 'Moscow',
    details: 'Invalid credentials',
  },
  {
    id: 8,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 9,
    event_type: 'SESSION_TIMEOUT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 10,
    event_type: 'UNLOCK_ATTEMPT',
    success: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: 'Invalid passphrase',
  },
  {
    id: 11,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    ip_address: '98.76.54.32',
    country: 'United States',
    city: 'New York',
    details: null,
  },
  {
    id: 12,
    event_type: 'LOGOUT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    ip_address: '98.76.54.32',
    country: 'United States',
    city: 'New York',
    details: null,
  },
  {
    id: 13,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 14,
    event_type: 'SESSION_LOCK',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 74).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 15,
    event_type: 'LOGIN_ATTEMPT',
    success: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    ip_address: '192.168.1.100',
    country: 'Canada',
    city: 'Toronto',
    details: 'Invalid credentials',
  },
  {
    id: 16,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 17,
    event_type: 'UNLOCK_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 122).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 18,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 19,
    event_type: 'SESSION_TIMEOUT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 20,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 21,
    event_type: 'LOGOUT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 216).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 22,
    event_type: 'REMOTE_UNLOCK',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 220).toISOString(),
    ip_address: '98.76.54.32',
    country: 'United States',
    city: 'New York',
    details: null,
  },
  {
    id: 23,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 240).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 24,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 264).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 25,
    event_type: 'UNLOCK_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 288).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 26,
    event_type: 'LOGIN_ATTEMPT',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 312).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: null,
  },
  {
    id: 27,
    event_type: 'SET_PASSPHRASE',
    success: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 336).toISOString(),
    ip_address: '73.45.123.89',
    country: 'United States',
    city: 'San Francisco',
    details: 'Initial setup',
  },
];
