/**
 * Demo Data
 *
 * Realistic seed data for demo mode.
 * This data is loaded into localStorage on first demo access.
 */

import type {
  DashboardData,
  RecurringItem,
  RollupItem,
  RollupData,
  CategoryGroup,
  UnmappedCategory,
} from '../types';

// ============================================================================
// Demo State Interface
// ============================================================================

export interface DemoState {
  dashboard: DashboardData;
  categoryGroups: CategoryGroup[];
  unmappedCategories: UnmappedCategory[];
  settings: {
    auto_sync_new: boolean;
    auto_track_threshold: number | null;
    auto_update_targets: boolean;
    auto_categorize_enabled: boolean;
    show_category_group: boolean;
  };
}

// ============================================================================
// Helper Functions
// ============================================================================

function getNextDueDate(monthsFromNow: number): string {
  const date = new Date();
  date.setMonth(date.getMonth() + monthsFromNow);
  const isoDate = date.toISOString().split('T')[0];
  return isoDate ?? date.toISOString().substring(0, 10);
}

function calculateProgress(saved: number, target: number): number {
  if (target === 0) return 100;
  return Math.min(100, Math.round((saved / target) * 100));
}

/**
 * Calculate the frozen monthly target for a recurring item.
 * This is calculated for ALL items (enabled or disabled) so the target is ready
 * when the item is enabled. Mirrors the logic from services/frozen_target_calculator.py
 *
 * For monthly expenses: Target = ideal rate (no buffer/catch-up)
 * For infrequent expenses: Target = ceil(shortfall / months_remaining)
 */
function calculateFrozenTarget(
  amount: number,
  frequencyMonths: number,
  monthsUntilDue: number,
  currentBalance: number
): number {
  if (frequencyMonths <= 1) {
    // Monthly items: target is simply the ideal rate (rounded up)
    return Math.ceil(amount);
  } else {
    // Non-monthly items: calculate catch-up rate
    const shortfall = Math.max(0, amount - currentBalance);
    const monthsRemaining = Math.max(1, monthsUntilDue);
    if (shortfall > 0) {
      return Math.ceil(shortfall / monthsRemaining);
    }
    return 0;
  }
}

// ============================================================================
// Category Groups
// ============================================================================

const DEMO_CATEGORY_GROUPS: CategoryGroup[] = [
  { id: 'group-recurring', name: 'Recurring Expenses' },
  { id: 'group-subscriptions', name: 'Subscriptions' },
  { id: 'group-insurance', name: 'Insurance' },
  { id: 'group-utilities', name: 'Utilities' },
];

// ============================================================================
// Recurring Items
// ============================================================================

const DEMO_RECURRING_ITEMS: RecurringItem[] = [
  // ============================================================================
  // ENABLED - Big items (individual tracking, not in rollup)
  // Some show catch-up scenarios where frozen_monthly_target > ideal_monthly_rate
  // ============================================================================

  // CATCH-UP EXAMPLE 1: Semi-annual expense, moderately behind
  // current_balance = $160 (rollover from previous months)
  // planned_budget = $160 (committed budget for this month)
  // contributed_this_month = $160 (matches budget - fully allocated)
  // Total saved = $320, needs $720
  // Tooltip: "$160 rolled over, $160 budgeted this month"
  {
    id: 'item-car-insurance',
    merchant_id: 'merchant-geico',
    logo_url: null,
    is_stale: false,
    name: 'Car Insurance',
    merchant_name: 'GEICO',
    category_name: 'Car Insurance',
    frequency_label: 'Every 6 months',
    category_id: 'cat-car-insurance',
    category_group_name: 'Insurance',
    category_missing: false,
    amount: 720,
    frequency: 'semi-annual',
    frequency_months: 6,
    next_due_date: getNextDueDate(3),
    months_until_due: 3,
    current_balance: 160,
    planned_budget: 160,
    monthly_contribution: 160,
    over_contribution: 0,
    progress_percent: 44,
    status: 'behind',
    is_enabled: true,
    ideal_monthly_rate: 120,
    amount_needed_now: 120,
    is_in_rollup: false,
    emoji: '🚗',
    frozen_monthly_target: 160,
    contributed_this_month: 160,
    monthly_progress_percent: 100,
  },

  // CATCH-UP EXAMPLE 2: Annual expense, significantly behind
  // current_balance = $75 (rollover from previous months)
  // planned_budget = $250 (committed budget for this month)
  // contributed_this_month = $250 (matches budget - fully allocated)
  // Total saved = $325, needs $1200
  // Tooltip: "$75 rolled over, $250 budgeted this month"
  {
    id: 'item-home-insurance',
    merchant_id: 'merchant-statefarm',
    logo_url: null,
    is_stale: false,
    name: 'Home Insurance',
    merchant_name: 'State Farm',
    category_name: 'Home Insurance',
    frequency_label: 'Yearly',
    category_id: 'cat-home-insurance',
    category_group_name: 'Insurance',
    category_missing: false,
    amount: 1200,
    frequency: 'annual',
    frequency_months: 12,
    next_due_date: getNextDueDate(4),
    months_until_due: 4,
    current_balance: 75,
    planned_budget: 250,
    monthly_contribution: 250,
    over_contribution: 0,
    progress_percent: 27,
    status: 'behind',
    is_enabled: true,
    ideal_monthly_rate: 100,
    amount_needed_now: 600,
    is_in_rollup: false,
    emoji: '🏠',
    frozen_monthly_target: 250,
    contributed_this_month: 250,
    monthly_progress_percent: 100,
  },
  // MONTHLY - No rollover (bill was paid last month)
  // current_balance = $0, contributed_this_month = $95, total = $95
  {
    id: 'item-phone',
    merchant_id: 'merchant-verizon',
    logo_url: null,
    is_stale: false,
    name: 'Phone Bill',
    merchant_name: 'Verizon',
    category_name: 'Phone',
    frequency_label: 'Monthly',
    category_id: 'cat-phone',
    category_group_name: 'Utilities',
    category_missing: false,
    amount: 95,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 95,
    monthly_contribution: 95,
    over_contribution: 0,
    progress_percent: 100,
    status: 'funded',
    is_enabled: true,
    ideal_monthly_rate: 95,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '📱',
    frozen_monthly_target: 95,
    contributed_this_month: 95,
    monthly_progress_percent: 100,
  },
  // MONTHLY - No rollover (bill was paid last month)
  // current_balance = $0, contributed_this_month = $79.99, total = $79.99
  {
    id: 'item-internet',
    merchant_id: 'merchant-xfinity',
    logo_url: null,
    is_stale: false,
    name: 'Internet',
    merchant_name: 'Xfinity',
    category_name: 'Internet',
    frequency_label: 'Monthly',
    category_id: 'cat-internet',
    category_group_name: 'Utilities',
    category_missing: false,
    amount: 79.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 79.99,
    monthly_contribution: 79.99,
    over_contribution: 0,
    progress_percent: 100,
    status: 'funded',
    is_enabled: true,
    ideal_monthly_rate: 79.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '📶',
    frozen_monthly_target: 79.99,
    contributed_this_month: 79.99,
    monthly_progress_percent: 100,
  },
  // AHEAD EXAMPLE: Monthly expense with rollover (user is ahead)
  // current_balance = $40 rollover (start of month)
  // planned_budget = $50 (budgeting the full monthly amount)
  // Total saved = $90, more than one month funded
  // This user is "ahead" because they have $40 extra in the buffer
  {
    id: 'item-gym',
    merchant_id: 'merchant-planet-fitness',
    logo_url: null,
    is_stale: false,
    name: 'Gym Membership',
    merchant_name: 'Planet Fitness',
    category_name: 'Gym',
    frequency_label: 'Monthly',
    category_id: 'cat-gym',
    category_group_name: 'Recurring Expenses',
    category_missing: false,
    amount: 50,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 40,
    planned_budget: 50,
    monthly_contribution: 50,
    over_contribution: 0,
    progress_percent: 100,
    status: 'ahead',
    is_enabled: true,
    ideal_monthly_rate: 50,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '💪',
    frozen_monthly_target: 50,
    contributed_this_month: 50,
    monthly_progress_percent: 100,
  },

  // ============================================================================
  // ENABLED - Rollup items (5 small subscriptions)
  // All monthly, no rollover (bills paid via rollup category)
  // ============================================================================
  {
    id: 'item-netflix',
    merchant_id: 'merchant-netflix',
    logo_url: null,
    is_stale: false,
    name: 'Netflix',
    merchant_name: 'Netflix',
    category_name: 'Netflix',
    frequency_label: 'Monthly',
    category_id: 'cat-netflix',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 15.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 15.99,
    monthly_contribution: 15.99,
    over_contribution: 0,
    progress_percent: 100,
    status: 'funded',
    is_enabled: true,
    ideal_monthly_rate: 15.99,
    amount_needed_now: 0,
    is_in_rollup: true,
    emoji: '🎬',
    frozen_monthly_target: 15.99,
    contributed_this_month: 15.99,
    monthly_progress_percent: 100,
  },
  {
    id: 'item-spotify',
    merchant_id: 'merchant-spotify',
    logo_url: null,
    is_stale: false,
    name: 'Spotify',
    merchant_name: 'Spotify',
    category_name: 'Spotify',
    frequency_label: 'Monthly',
    category_id: 'cat-spotify',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 11.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 11.99,
    monthly_contribution: 11.99,
    over_contribution: 0,
    progress_percent: 100,
    status: 'funded',
    is_enabled: true,
    ideal_monthly_rate: 11.99,
    amount_needed_now: 0,
    is_in_rollup: true,
    emoji: '🎵',
    frozen_monthly_target: 11.99,
    contributed_this_month: 11.99,
    monthly_progress_percent: 100,
  },
  {
    id: 'item-disney',
    merchant_id: 'merchant-disney',
    logo_url: null,
    is_stale: false,
    name: 'Disney+',
    merchant_name: 'Disney',
    category_name: 'Disney+',
    frequency_label: 'Monthly',
    category_id: 'cat-disney',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 13.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 13.99,
    monthly_contribution: 13.99,
    over_contribution: 0,
    progress_percent: 100,
    status: 'funded',
    is_enabled: true,
    ideal_monthly_rate: 13.99,
    amount_needed_now: 0,
    is_in_rollup: true,
    emoji: '✨',
    frozen_monthly_target: 13.99,
    contributed_this_month: 13.99,
    monthly_progress_percent: 100,
  },
  {
    id: 'item-icloud',
    merchant_id: 'merchant-apple',
    logo_url: null,
    is_stale: false,
    name: 'iCloud Storage',
    merchant_name: 'Apple',
    category_name: 'iCloud',
    frequency_label: 'Monthly',
    category_id: 'cat-icloud',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 2.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 2.99,
    monthly_contribution: 2.99,
    over_contribution: 0,
    progress_percent: 100,
    status: 'funded',
    is_enabled: true,
    ideal_monthly_rate: 2.99,
    amount_needed_now: 0,
    is_in_rollup: true,
    emoji: '☁️',
    frozen_monthly_target: 2.99,
    contributed_this_month: 2.99,
    monthly_progress_percent: 100,
  },
  {
    id: 'item-hulu',
    merchant_id: 'merchant-hulu',
    logo_url: null,
    is_stale: false,
    name: 'Hulu',
    merchant_name: 'Hulu',
    category_name: 'Hulu',
    frequency_label: 'Monthly',
    category_id: 'cat-hulu',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 17.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 17.99,
    monthly_contribution: 17.99,
    over_contribution: 0,
    progress_percent: 100,
    status: 'funded',
    is_enabled: true,
    ideal_monthly_rate: 17.99,
    amount_needed_now: 0,
    is_in_rollup: true,
    emoji: '📺',
    frozen_monthly_target: 17.99,
    contributed_this_month: 17.99,
    monthly_progress_percent: 100,
  },

  // ============================================================================
  // ENABLED - Catch-up example (annual expense)
  // ============================================================================

  // CATCH-UP EXAMPLE 3: Annual expense, mildly behind
  // User has $30 saved for $139 annual expense with 5 months to go
  // Needs $109 in 5 months = ~$22/mo vs ~$12/mo ideal
  // current_balance = total ($30), contributed_this_month = $22, rollover = $8
  {
    id: 'item-amazon-prime',
    merchant_id: 'merchant-amazon',
    logo_url: null,
    is_stale: false,
    name: 'Amazon Prime',
    merchant_name: 'Amazon',
    category_name: 'Amazon Prime',
    frequency_label: 'Yearly',
    category_id: 'cat-amazon-prime',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 139,
    frequency: 'annual',
    frequency_months: 12,
    next_due_date: getNextDueDate(5),
    months_until_due: 5,
    current_balance: 30,
    planned_budget: 22,
    monthly_contribution: 22,
    over_contribution: 0,
    progress_percent: 22,
    status: 'on_track',
    is_enabled: true,
    ideal_monthly_rate: 12,
    amount_needed_now: 51,
    is_in_rollup: false,
    emoji: '📦',
    frozen_monthly_target: 22,
    contributed_this_month: 22,
    monthly_progress_percent: 100,
  },

  // ============================================================================
  // DISABLED - The rest (not tracking yet)
  // ============================================================================
  {
    id: 'item-hbo',
    merchant_id: 'merchant-hbo',
    logo_url: null,
    is_stale: false,
    name: 'Max (HBO)',
    merchant_name: 'Max',
    category_name: 'Max',
    frequency_label: 'Monthly',
    category_id: 'cat-hbo',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 15.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 15.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🎭',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-youtube-premium',
    merchant_id: 'merchant-google',
    logo_url: null,
    is_stale: false,
    name: 'YouTube Premium',
    merchant_name: 'Google',
    category_name: 'YouTube Premium',
    frequency_label: 'Monthly',
    category_id: 'cat-youtube',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 13.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 13.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '▶️',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-costco',
    merchant_id: 'merchant-costco',
    logo_url: null,
    is_stale: false,
    name: 'Costco Membership',
    merchant_name: 'Costco',
    category_name: 'Costco',
    frequency_label: 'Yearly',
    category_id: 'cat-costco',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 65,
    frequency: 'annual',
    frequency_months: 12,
    next_due_date: getNextDueDate(8),
    months_until_due: 8,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 5.42,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🛒',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-renters',
    merchant_id: 'merchant-lemonade',
    logo_url: null,
    is_stale: false,
    name: 'Renters Insurance',
    merchant_name: 'Lemonade',
    category_name: 'Renters Insurance',
    frequency_label: 'Yearly',
    category_id: 'cat-renters',
    category_group_name: 'Insurance',
    category_missing: false,
    amount: 144,
    frequency: 'annual',
    frequency_months: 12,
    next_due_date: getNextDueDate(7),
    months_until_due: 7,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 12,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🏠',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-aaa',
    merchant_id: 'merchant-aaa',
    logo_url: null,
    is_stale: false,
    name: 'AAA Membership',
    merchant_name: 'AAA',
    category_name: 'AAA',
    frequency_label: 'Yearly',
    category_id: 'cat-aaa',
    category_group_name: 'Insurance',
    category_missing: false,
    amount: 79,
    frequency: 'annual',
    frequency_months: 12,
    next_due_date: getNextDueDate(4),
    months_until_due: 4,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 6.58,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🚙',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-playstation',
    merchant_id: 'merchant-sony',
    logo_url: null,
    is_stale: false,
    name: 'PlayStation Plus',
    merchant_name: 'Sony',
    category_name: 'PlayStation Plus',
    frequency_label: 'Yearly',
    category_id: 'cat-playstation',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 59.99,
    frequency: 'annual',
    frequency_months: 12,
    next_due_date: getNextDueDate(9),
    months_until_due: 9,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 5,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🎮',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-apple-tv',
    merchant_id: 'merchant-apple',
    logo_url: null,
    is_stale: false,
    name: 'Apple TV+',
    merchant_name: 'Apple',
    category_name: 'Apple TV+',
    frequency_label: 'Monthly',
    category_id: 'cat-appletv',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 9.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 9.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🍎',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-peacock',
    merchant_id: 'merchant-nbc',
    logo_url: null,
    is_stale: false,
    name: 'Peacock',
    merchant_name: 'NBCUniversal',
    category_name: 'Peacock',
    frequency_label: 'Monthly',
    category_id: 'cat-peacock',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 7.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 7.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🦚',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-paramount',
    merchant_id: 'merchant-paramount',
    logo_url: null,
    is_stale: false,
    name: 'Paramount+',
    merchant_name: 'Paramount',
    category_name: 'Paramount+',
    frequency_label: 'Monthly',
    category_id: 'cat-paramount',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 11.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 11.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '⛰️',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-nyt',
    merchant_id: 'merchant-nyt',
    logo_url: null,
    is_stale: false,
    name: 'NY Times Digital',
    merchant_name: 'New York Times',
    category_name: 'NY Times',
    frequency_label: 'Yearly',
    category_id: 'cat-nyt',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 100,
    frequency: 'annual',
    frequency_months: 12,
    next_due_date: getNextDueDate(6),
    months_until_due: 6,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 8.33,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '📰',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-electric',
    merchant_id: 'merchant-electric',
    logo_url: null,
    is_stale: false,
    name: 'Electric Bill',
    merchant_name: 'Local Electric',
    category_name: 'Electric',
    frequency_label: 'Monthly',
    category_id: 'cat-electric',
    category_group_name: 'Utilities',
    category_missing: false,
    amount: 120,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 120,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '⚡',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-water',
    merchant_id: 'merchant-water',
    logo_url: null,
    is_stale: false,
    name: 'Water Bill',
    merchant_name: 'City Water',
    category_name: 'Water',
    frequency_label: 'Monthly',
    category_id: 'cat-water',
    category_group_name: 'Utilities',
    category_missing: false,
    amount: 45,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 45,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '💧',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-trash',
    merchant_id: 'merchant-waste',
    logo_url: null,
    is_stale: false,
    name: 'Trash & Recycling',
    merchant_name: 'Waste Management',
    category_name: 'Trash',
    frequency_label: 'Quarterly',
    category_id: 'cat-trash',
    category_group_name: 'Utilities',
    category_missing: false,
    amount: 90,
    frequency: 'quarterly',
    frequency_months: 3,
    next_due_date: getNextDueDate(2),
    months_until_due: 2,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 30,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🗑️',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-pet-insurance',
    merchant_id: 'merchant-pet',
    logo_url: null,
    is_stale: false,
    name: 'Pet Insurance',
    merchant_name: 'Healthy Paws',
    category_name: 'Pet Insurance',
    frequency_label: 'Monthly',
    category_id: 'cat-pet',
    category_group_name: 'Insurance',
    category_missing: false,
    amount: 45,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 45,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🐕',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-apple-music',
    merchant_id: 'merchant-apple',
    logo_url: null,
    is_stale: false,
    name: 'Apple Music',
    merchant_name: 'Apple',
    category_name: 'Apple Music',
    frequency_label: 'Monthly',
    category_id: 'cat-applemusic',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 10.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 10.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🎧',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-xbox',
    merchant_id: 'merchant-microsoft',
    logo_url: null,
    is_stale: false,
    name: 'Xbox Game Pass',
    merchant_name: 'Microsoft',
    category_name: 'Xbox Game Pass',
    frequency_label: 'Monthly',
    category_id: 'cat-xbox',
    category_group_name: 'Subscriptions',
    category_missing: false,
    amount: 16.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 16.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🎮',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
  {
    id: 'item-car-wash',
    merchant_id: 'merchant-carwash',
    logo_url: null,
    is_stale: false,
    name: 'Car Wash Membership',
    merchant_name: 'Mister Car Wash',
    category_name: 'Car Wash',
    frequency_label: 'Monthly',
    category_id: 'cat-carwash',
    category_group_name: 'Recurring Expenses',
    category_missing: false,
    amount: 29.99,
    frequency: 'monthly',
    frequency_months: 1,
    next_due_date: getNextDueDate(0),
    months_until_due: 0,
    current_balance: 0,
    planned_budget: 0,
    monthly_contribution: 0,
    over_contribution: 0,
    progress_percent: 0,
    status: 'disabled',
    is_enabled: false,
    ideal_monthly_rate: 29.99,
    amount_needed_now: 0,
    is_in_rollup: false,
    emoji: '🚿',
    frozen_monthly_target: 0,
    contributed_this_month: 0,
    monthly_progress_percent: 0,
  },
];

// ============================================================================
// Rollup Data
// ============================================================================

function createRollupData(items: RecurringItem[]): RollupData {
  const rollupItems = items.filter((item) => item.is_in_rollup);

  const rollupItemsData: RollupItem[] = rollupItems.map((item) => ({
    id: item.id,
    name: item.name,
    merchant_id: item.merchant_id,
    logo_url: item.logo_url,
    amount: item.amount,
    frequency: item.frequency,
    frequency_months: item.frequency_months,
    next_due_date: item.next_due_date,
    months_until_due: item.months_until_due,
    ideal_monthly_rate: item.ideal_monthly_rate,
    frozen_monthly_target: item.frozen_monthly_target,
    status: item.status,
  }));

  const totalIdealRate = rollupItemsData.reduce(
    (sum, item) => sum + item.ideal_monthly_rate,
    0
  );
  const totalFrozenMonthly = rollupItemsData.reduce(
    (sum, item) => sum + item.frozen_monthly_target,
    0
  );
  const totalTarget = rollupItemsData.reduce((sum, item) => sum + item.amount, 0);
  // Total saved = current_balance (rollover) + contributed_this_month
  const totalSaved = rollupItems.reduce(
    (sum, item) => sum + item.current_balance + item.contributed_this_month,
    0
  );

  return {
    enabled: true,
    items: rollupItemsData,
    total_ideal_rate: Math.round(totalIdealRate * 100) / 100,
    total_frozen_monthly: Math.round(totalFrozenMonthly * 100) / 100,
    total_target: Math.round(totalTarget * 100) / 100,
    total_saved: Math.round(totalSaved * 100) / 100,
    budgeted: Math.round(totalFrozenMonthly * 100) / 100,
    current_balance: Math.round(totalSaved * 100) / 100,
    progress_percent: calculateProgress(totalSaved, totalTarget),
    category_id: 'cat-rollup',
    emoji: '📦',
    category_name: 'Small Subscriptions' as string,
  };
}

// ============================================================================
// Unmapped Categories
// ============================================================================

const DEMO_UNMAPPED_CATEGORIES: UnmappedCategory[] = [
  {
    id: 'uncat-streaming',
    name: 'Streaming Services',
    group_id: 'group-subscriptions',
    group_name: 'Subscriptions',
    icon: '📺',
    group_order: 1,
    category_order: 1,
    planned_budget: 0,
  },
  {
    id: 'uncat-software',
    name: 'Software Subscriptions',
    group_id: 'group-subscriptions',
    group_name: 'Subscriptions',
    icon: '💻',
    group_order: 1,
    category_order: 2,
    planned_budget: 0,
  },
];

// ============================================================================
// Initial Demo State
// ============================================================================

function createDashboardData(items: RecurringItem[]): DashboardData {
  // Calculate frozen_monthly_target for items that don't have one yet (disabled items)
  // This ensures the target is ready when items are enabled
  // Enabled items keep their curated values for demo purposes
  const processedItems = items.map((item) => ({
    ...item,
    frozen_monthly_target: item.frozen_monthly_target || calculateFrozenTarget(
      item.amount,
      item.frequency_months,
      item.months_until_due,
      item.current_balance
    ),
  }));

  const activeItems = processedItems.filter((item) => item.is_enabled);
  const inactiveItems = processedItems.filter((item) => !item.is_enabled);

  const totalMonthlyContribution = activeItems.reduce(
    (sum, item) => sum + item.monthly_contribution,
    0
  );
  // Total saved = current_balance (rollover) + contributed_this_month
  const totalSaved = activeItems.reduce(
    (sum, item) => sum + item.current_balance + item.contributed_this_month,
    0
  );
  const totalTarget = activeItems.reduce((sum, item) => sum + item.amount, 0);

  return {
    items: processedItems,
    summary: {
      total_monthly_contribution: Math.round(totalMonthlyContribution * 100) / 100,
      total_saved: Math.round(totalSaved * 100) / 100,
      total_target: Math.round(totalTarget * 100) / 100,
      overall_progress: calculateProgress(totalSaved, totalTarget),
      active_count: activeItems.length,
      inactive_count: inactiveItems.length,
    },
    config: {
      target_group_id: 'group-recurring',
      target_group_name: 'Recurring Expenses',
      is_configured: true,
      auto_sync_new: true,
      auto_track_threshold: 50,
      auto_update_targets: true,
      auto_categorize_enabled: false,
      show_category_group: true,
      user_first_name: 'Demo User',
    },
    last_sync: new Date().toISOString(),
    ready_to_assign: {
      ready_to_assign: 523.47,
      planned_income: 5000,
      actual_income: 4876.53,
      planned_expenses: 3200,
      actual_expenses: 2845.32,
      planned_savings: 800,
      remaining_income: 1231.21,
    },
    rollup: createRollupData(items),
    notices: [],
  };
}

export function createInitialDemoState(): DemoState {
  return {
    dashboard: createDashboardData(DEMO_RECURRING_ITEMS),
    categoryGroups: DEMO_CATEGORY_GROUPS,
    unmappedCategories: DEMO_UNMAPPED_CATEGORIES,
    settings: {
      auto_sync_new: true,
      auto_track_threshold: 50,
      auto_update_targets: true,
      auto_categorize_enabled: false,
      show_category_group: true,
    },
  };
}

export const DEMO_INITIAL_STATE = createInitialDemoState();
