/**
 * GuidePage - Displays user guide documentation
 *
 * Protected route that renders bundled MDX user guides.
 * Opens in new tab from help dropdown.
 */

import { useParams, Link } from 'react-router-dom';
import { ChevronLeft, BookOpen, Home } from 'lucide-react';
import { MDXProvider } from '../components/docs/MDXProvider';

// Import all guide MDX files
// These will be generated by the docs-gen scripts
const guideModules = import.meta.glob('../docs/guide/*.mdx', { eager: true }) as Record<
  string,
  { default: React.ComponentType; frontmatter?: { title?: string; description?: string } }
>;

interface GuideInfo {
  slug: string;
  title: string;
  description: string | undefined;
  Component: React.ComponentType;
}

// Parse guide modules into a structured list
function getGuides(): GuideInfo[] {
  return Object.entries(guideModules)
    .map(([path, module]) => {
      const slug = path.replace('../docs/guide/', '').replace('.mdx', '');
      return {
        slug,
        title: module.frontmatter?.title ?? formatTitle(slug),
        description: module.frontmatter?.description,
        Component: module.default,
      };
    })
    .sort((a, b) => a.title.localeCompare(b.title));
}

function formatTitle(slug: string): string {
  return slug
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function GuideIndex({ guides }: { guides: GuideInfo[] }) {
  return (
    <div className="max-w-3xl mx-auto">
      <div className="flex items-center gap-3 mb-6">
        <BookOpen className="h-8 w-8" style={{ color: 'var(--monarch-orange)' }} />
        <h1 className="text-2xl font-bold" style={{ color: 'var(--monarch-text-dark)' }}>
          User Guide
        </h1>
      </div>

      <p className="mb-8" style={{ color: 'var(--monarch-text-muted)' }}>
        Learn how to use Eclosion to manage your recurring expenses and budgeting.
      </p>

      {guides.length === 0 ? (
        <div
          className="p-8 rounded-lg text-center"
          style={{ backgroundColor: 'var(--monarch-bg-card)', border: '1px solid var(--monarch-border)' }}
        >
          <p style={{ color: 'var(--monarch-text-muted)' }}>
            User guides are being generated. Check back soon!
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {guides.map(guide => (
            <Link
              key={guide.slug}
              to={`/guide/${guide.slug}`}
              className="block p-4 rounded-lg transition-colors hover:opacity-90"
              style={{
                backgroundColor: 'var(--monarch-bg-card)',
                border: '1px solid var(--monarch-border)',
              }}
            >
              <div className="font-medium" style={{ color: 'var(--monarch-text-dark)' }}>
                {guide.title}
              </div>
              {guide.description && (
                <div className="text-sm mt-1" style={{ color: 'var(--monarch-text-muted)' }}>
                  {guide.description}
                </div>
              )}
            </Link>
          ))}
        </div>
      )}

      <div className="mt-8 pt-6" style={{ borderTop: '1px solid var(--monarch-border)' }}>
        <Link
          to="/dashboard"
          className="inline-flex items-center gap-2 text-sm hover:opacity-80"
          style={{ color: 'var(--monarch-orange)' }}
        >
          <Home className="h-4 w-4" />
          Back to Dashboard
        </Link>
      </div>
    </div>
  );
}

function GuideContent({ guide }: { guide: GuideInfo }) {
  const { Component } = guide;

  return (
    <div className="max-w-3xl mx-auto">
      <Link
        to="/guide"
        className="inline-flex items-center gap-1 text-sm mb-6 hover:opacity-80"
        style={{ color: 'var(--monarch-orange)' }}
      >
        <ChevronLeft className="h-4 w-4" />
        Back to Guide
      </Link>

      <MDXProvider>
        <Component />
      </MDXProvider>
    </div>
  );
}

export function GuidePage() {
  const { slug } = useParams<{ slug?: string }>();
  const guides = getGuides();

  // Find the requested guide
  const guide = slug ? guides.find(g => g.slug === slug) : null;

  return (
    <div
      className="min-h-screen py-8 px-4"
      style={{ backgroundColor: 'var(--monarch-bg-page)' }}
    >
      {slug && guide ? (
        <GuideContent guide={guide} />
      ) : slug ? (
        <div className="max-w-3xl mx-auto">
          <h1 className="text-xl font-bold mb-4" style={{ color: 'var(--monarch-text-dark)' }}>
            Guide Not Found
          </h1>
          <p style={{ color: 'var(--monarch-text-muted)' }}>
            The requested guide could not be found.
          </p>
          <Link
            to="/guide"
            className="inline-flex items-center gap-1 text-sm mt-4 hover:opacity-80"
            style={{ color: 'var(--monarch-orange)' }}
          >
            <ChevronLeft className="h-4 w-4" />
            Back to Guide
          </Link>
        </div>
      ) : (
        <GuideIndex guides={guides} />
      )}
    </div>
  );
}
